<a href="https://colab.research.google.com/github/odhissm/venture_funding/blob/main/funding_app/GC_venture_funding_with_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [366]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from pathlib import Path

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [367]:
# Upload credit_card_transactions.csv to Colab
from google.colab import files

csv_file = files.upload()

Saving applicants_data.csv to applicants_data (5).csv

In [368]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(
    Path('applicants_data.csv')
)

# Review the DataFrame
display(applicant_data_df.head())
display(applicant_data_df.tail())

        EIN                                      NAME  ... ASK_AMT IS_SUCCESSFUL
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB  ...    5000             1
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR  ...  108590             1
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS  ...    5000             0
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION  ...    6692             1
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT  ...  142590             1

[5 rows x 12 columns]

             EIN  ... IS_SUCCESSFUL
34294  996009318  ...             0
34295  996010315  ...             0
34296  996012607  ...             0
34297  996015768  ...             1
34298  996086871  ...             0

[5 rows x 12 columns]

In [369]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [370]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(["EIN", "NAME"], axis=1) 

# Review the DataFrame
display(applicant_data_df.head())

  APPLICATION_TYPE       AFFILIATION  ... ASK_AMT IS_SUCCESSFUL
0              T10       Independent  ...    5000             1
1               T3       Independent  ...  108590             1
2               T5  CompanySponsored  ...    5000             0
3               T3  CompanySponsored  ...    6692             1
4               T3       Independent  ...  142590             1

[5 rows x 10 columns]

In [371]:
# Create a list of categorical variables 
categorical_variables = ["APPLICATION_TYPE", "AFFILIATION", "CLASSIFICATION", "USE_CASE", "ORGANIZATION", "INCOME_AMT"]

# Display the categorical variables list
display(categorical_variables)

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT']

In [372]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [373]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [374]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names(categorical_variables)
    
)

# Review the DataFrame
encoded_df.head()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

   APPLICATION_TYPE_T10  ...  INCOME_AMT_5M-10M
0                   1.0  ...                0.0
1                   0.0  ...                0.0
2                   0.0  ...                0.0
3                   0.0  ...                0.0
4                   0.0  ...                0.0

[5 rows x 112 columns]

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [375]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df["STATUS"], encoded_df["ASK_AMT"], encoded_df["IS_SUCCESSFUL"] =  [applicant_data_df["STATUS"], applicant_data_df["ASK_AMT"], applicant_data_df["IS_SUCCESSFUL"]]

# Review the Dataframe
encoded_df.head()

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T12  ...  ASK_AMT  IS_SUCCESSFUL
0                   1.0                   0.0  ...     5000              1
1                   0.0                   0.0  ...   108590              1
2                   0.0                   0.0  ...     5000              0
3                   0.0                   0.0  ...     6692              1
4                   0.0                   0.0  ...   142590              1

[5 rows x 115 columns]

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [376]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Display a sample of y
display(y)

0        1
1        1
2        0
3        1
4        1
        ..
34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, Length: 34299, dtype: int64

In [377]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.iloc[:, 0:79].values

# Review the features DataFrame
display(X)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

### Step 6: Split the features and target sets into training and testing datasets.

In [378]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1
    
)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [379]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [380]:
# Define the the number of inputs (features) to the model
number_input_features = 79

# Review the number of features
number_input_features

79

In [381]:
# Define the number of neurons in the output layer
number_output_neurons = 2

In [382]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  8

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

8

In [383]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  4

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

4

In [384]:
# Create the Sequential model instance
dnn = Sequential()

In [385]:
# Add the first hidden layer
dnn.add(
    Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

In [386]:
# Add the second hidden layer
dnn.add(
    Dense(units=hidden_nodes_layer2, activation="relu")
)

In [387]:
# Add the output layer to the model specifying the number of output neurons and activation function
dnn.add(
    Dense(units=number_output_neurons, activation="linear")
)

In [388]:
# Display the Sequential model summary
dnn.summary()

Model: "sequential_26"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_62 (Dense)            (None, 8)                 640

 dense_63 (Dense)            (None, 4)                 36

 dense_64 (Dense)            (None, 2)                 10

=================================================================
Total params: 686
Trainable params: 686
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [389]:
# Compile the Sequential model
dnn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [390]:
# Fit the model using 50 epochs and the training data
model_2 = dnn.fit(X_train_scaled, y_train,  epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 1.4273 - accuracy: 0.5690
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7723 - accuracy: 0.5220
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7393 - accuracy: 0.5182
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7011 - accuracy: 0.5802
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6634 - accuracy: 0.6082
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6507 - accuracy: 0.6480
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6432 - accuracy: 0.6656
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6422 - accuracy: 0.6528
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6383 - accuracy: 0.6050
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6379 - accuracy: 0.6437
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6369 - accuracy: 0.6270
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6372 - accuracy: 0.6189
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6355 - accuracy: 0.5686
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6336 - accuracy: 0.5493
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6331 - accuracy: 0.6279
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6331 - accuracy: 0.6429
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6355 - accuracy: 0.6003
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6327 - accuracy: 0.5861
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6163 - accuracy: 0.5318
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6125 - accuracy: 0.3463
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6108 - accuracy: 0.4980
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6104 - accuracy: 0.5417
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6094 - accuracy: 0.5826
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6090 - accuracy: 0.5851
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6087 - accuracy: 0.5522
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6102 - accuracy: 0.5994
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6087 - accuracy: 0.5692
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6059 - accuracy: 0.5124
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6057 - accuracy: 0.5351
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6057 - accuracy: 0.5016
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6055 - accuracy: 0.5100
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6067 - accuracy: 0.5315
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6056 - accuracy: 0.5418
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6053 - accuracy: 0.5279
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6078 - accuracy: 0.5749
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6060 - accuracy: 0.5206
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6055 - accuracy: 0.5257
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6060 - accuracy: 0.4920
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6085 - accuracy: 0.5055
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6101 - accuracy: 0.5142
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6129 - accuracy: 0.6324
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6079 - accuracy: 0.4932
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6089 - accuracy: 0.4572
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6144 - accuracy: 0.5001
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6085 - accuracy: 0.6023
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6081 - accuracy: 0.5525
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6082 - accuracy: 0.5428
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6081 - accuracy: 0.5616
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6087 - accuracy: 0.5714
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6085 - accuracy: 0.5023

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [391]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = dnn.evaluate(X_test_scaled, y_test, verbose=0)


# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Loss: 0.607407808303833, Accuracy: 0.3696793019771576

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [392]:
# Set the model's file path
file_path = Path("Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
dnn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [393]:
# Define the the number of inputs (features) to the model
#number_input_features = len(X_train.iloc[0])
number_input_features = len(pd.DataFrame(X_train).iloc[0])

# Review the number of features
number_input_features

79

In [394]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [395]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 4

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

4

In [396]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [397]:
# First hidden layer
nn_A1.add(
    Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu")
)


# Output layer
nn_A1.add(
    Dense(units=number_output_neurons_A1, activation="linear")
)


# Check the structure of the model
nn_A1.summary()

Model: "sequential_27"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_65 (Dense)            (None, 4)                 320

 dense_66 (Dense)            (None, 1)                 5

=================================================================
Total params: 325
Trainable params: 325
Non-trainable params: 0
_________________________________________________________________

In [398]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [399]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 2.9289 - accuracy: 0.5060
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 2.1897 - accuracy: 0.6472
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 2.1749 - accuracy: 0.6631
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 2.1675 - accuracy: 0.6638
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 1.9861 - accuracy: 0.6690
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 1.3750 - accuracy: 0.6739
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0990 - accuracy: 0.6861
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0977 - accuracy: 0.6884
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0799 - accuracy: 0.6833
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0683 - accuracy: 0.6913
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0668 - accuracy: 0.6920
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0655 - accuracy: 0.6920
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0645 - accuracy: 0.6889
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0631 - accuracy: 0.6906
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0617 - accuracy: 0.6944
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0604 - accuracy: 0.6944
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0600 - accuracy: 0.6937
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0596 - accuracy: 0.6950
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0588 - accuracy: 0.6945
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0587 - accuracy: 0.6949
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0586 - accuracy: 0.6947
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0590 - accuracy: 0.6948
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0584 - accuracy: 0.6953
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0568 - accuracy: 0.6949
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0566 - accuracy: 0.6951
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0561 - accuracy: 0.6957
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0560 - accuracy: 0.6958
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0561 - accuracy: 0.6957
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0559 - accuracy: 0.6955
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0562 - accuracy: 0.6955
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0597 - accuracy: 0.6971
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0560 - accuracy: 0.6979
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0550 - accuracy: 0.6977
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0549 - accuracy: 0.6976
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0547 - accuracy: 0.6978
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0545 - accuracy: 0.6976
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0544 - accuracy: 0.6978
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0543 - accuracy: 0.6979
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0537 - accuracy: 0.6979
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0569 - accuracy: 0.6977
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0575 - accuracy: 0.6975
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0503 - accuracy: 0.6976
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0602 - accuracy: 0.6944
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0612 - accuracy: 0.6961
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0484 - accuracy: 0.6963
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0422 - accuracy: 0.6970
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0564 - accuracy: 0.6956
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0565 - accuracy: 0.6968
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0563 - accuracy: 0.6969
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0563 - accuracy: 0.6971

#### Alternative Model 2

In [400]:
# Define the the number of inputs (features) to the model
#number_input_features = len(X_train.iloc[0])
number_input_features = len(pd.DataFrame(X_train).iloc[0])

# Review the number of features
number_input_features

79

In [401]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [402]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

2

In [403]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [404]:
# First hidden layer
nn_A2.add(
    Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="relu")
)

# Output layer
nn_A2.add(
    Dense(units=number_output_neurons_A1, activation="linear")
)

# Check the structure of the model
nn_A2.summary()

Model: "sequential_28"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_67 (Dense)            (None, 2)                 160

 dense_68 (Dense)            (None, 1)                 3

=================================================================
Total params: 163
Trainable params: 163
Non-trainable params: 0
_________________________________________________________________

In [405]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [406]:
# Fit the model
mode_2_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 1.3424 - accuracy: 0.6588
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1893 - accuracy: 0.7016
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1742 - accuracy: 0.7017
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1690 - accuracy: 0.7013
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1669 - accuracy: 0.7016
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1661 - accuracy: 0.7014
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1661 - accuracy: 0.7018
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1657 - accuracy: 0.7026
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1678 - accuracy: 0.7023
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1662 - accuracy: 0.7022
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1654 - accuracy: 0.7029
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1655 - accuracy: 0.7028
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1664 - accuracy: 0.7029
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1652 - accuracy: 0.7031
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1655 - accuracy: 0.7032
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1653 - accuracy: 0.7028
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1656 - accuracy: 0.7031
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 1.1653 - accuracy: 0.7028
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1661 - accuracy: 0.7022
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1653 - accuracy: 0.7034
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1652 - accuracy: 0.7031
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1660 - accuracy: 0.7025
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1651 - accuracy: 0.7025
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1660 - accuracy: 0.7027
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1648 - accuracy: 0.7029
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1652 - accuracy: 0.7032
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1655 - accuracy: 0.7028
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1652 - accuracy: 0.7027
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1654 - accuracy: 0.7025
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1656 - accuracy: 0.7034
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1070 - accuracy: 0.7017
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0905 - accuracy: 0.7020
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0900 - accuracy: 0.7020
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0903 - accuracy: 0.7020
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0903 - accuracy: 0.7020
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0903 - accuracy: 0.7020
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0911 - accuracy: 0.7020
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0903 - accuracy: 0.7022
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0893 - accuracy: 0.7020
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0803 - accuracy: 0.7023
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0805 - accuracy: 0.7020
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0830 - accuracy: 0.7018
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0804 - accuracy: 0.7020
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0807 - accuracy: 0.7018
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 1.0805 - accuracy: 0.7019
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0802 - accuracy: 0.7020
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0805 - accuracy: 0.7018
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0803 - accuracy: 0.7020
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0808 - accuracy: 0.7018
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0806 - accuracy: 0.7018

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [407]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = dnn.evaluate(X_test_scaled, y_test, verbose=0)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
Loss: 0.607407808303833, Accuracy: 0.3696793019771576

In [408]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy =nn_A1.evaluate(X_test_scaled, y_test, verbose=0)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
Loss: 1.0523439645767212, Accuracy: 0.6979591846466064

In [409]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=0)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
Loss: 1.0559895038604736, Accuracy: 0.7023906707763672

### Step 3: Save each of your alternative models as an HDF5 file.

In [ ]:
# Set the file path for the first alternative model
file_path = # YOUR CODE HERE

# Export your model to a HDF5 file
# YOUR CODE HERE

In [ ]:
# Set the file path for the second alternative model
file_path = # YOUR CODE HERE

# Export your model to a HDF5 file
# YOUR CODE HERE